### ISSUE TITLE
Display only open issue from project

### ISSUE THREAD

**Issue by PadawanDeluxe** [mozgan/dokuwiki-plugin-gitlabapi#1]
Hey there, while playing around with the API  I considered to have only listed open issues on a project. It may be not of interest what has already been done so some kind of filter would be nice to have. 

thanks for your work here mate!

Greetings
Carsten

**Comment by mozgan** [comment]
Hi @PadawanDeluxe 
Thanks for feedback. I have just updated the repo. So, the plugin shows only **opened** issues of a given project.
