### ISSUE TITLE
Error: Call to undefined function curl_init()

### ISSUE THREAD

**Issue by tufekk** [mozgan/dokuwiki-plugin-gitlabapi#2]
Hi,
In first place thank you very much for your project!
I try to use gitlab-api with regular gitlab.com account and a dokuwiki instance selfhosted. I followed the [documentation](https://www.dokuwiki.org/plugin:gitlabapi) but still get an error related to curl_init().

What I did:
1. Installed gitlab-api plugin through extension manager
2. Used server.json file to set my my gitlab server url and api_token up
3. Created a dokuwiki page containing <gitlab-api project-path="my/project" /> (same issue using the GUI button)

What I get:
- On the dokuwiki page:
```
Error: Call to undefined function curl_init()
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the gitlabapi plugin.
More info has been written to the DokuWiki error log.
```
- On error.log:
`/var/www/dokuwiki/lib/plugins/gitlabapi/gitlab/gitlabapi.php(19)        Error: Call to undefined function curl_init()`
full log here: https://paste.debian.net/plain/1300808

Do you think my issue could come from a bug or from my side?

Thank you by advance

Hardware/Software description:
- [ Hardware] : Orangepi4lts with a Rockchip3399
- [Kernel] : 5.15.93-rockchip64
- [OS] : Yunohost 11 (Armbian 23)
- [Webserver] : nginx/1.18.0
- [php version] : 8.2
- [php-curl version] : 2:7.4+76

**Comment by mozgan** [comment]
Hi @tufekk,
thank you for feedback!

> Call to undefined function curl_init()

means that `curl` has not been installed in your OS yet or not enabled in PHP. Please try to install `curl` as follows:

`sudo apt update && sudo apt upgrade && sudo apt install curl`

After that, you can check if it is installed correctly:

> curl -I https://www.google.com

Additionally, if `curl` is installed, but not enabled in your PHP, you can add the following line to your _php.ini_ file:

> extension=curl.so

Finally, you have to write in url tag "**https://gitlab.com**" if you use _gitlab.com_ in _server.json_.

Besides all of these, I found another bugs and (I wish) corrected them. Please install the latest version of plugin and let me know if there is any bug.

Thank you!
